{{- if not .Values.providers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: peerpods
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  CLOUD_PROVIDER: "{{ .Values.provider }}"
{{- $config := dict }}
{{- if .Values.providerConfigs }}
{{- $config = index .Values.providerConfigs .Values.provider | default dict }}
{{- end }}
{{- range $key, $value := $config }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
