{{- range $provider := .Values.providers }}
{{- if include "peerpods.providerEnabled" $provider }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
{{ include "peerpods.providerServiceAccountAnnotations" $provider | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-pod-viewer
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-pod-viewer
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: cloud-api-adaptor-{{ $provider.name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cloud-api-adaptor-{{ $provider.name }}-pod-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-peerpod-editor
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
rules:
- apiGroups: ["confidentialcontainers.org"]
  resources: ["peerpods"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-peerpod-editor
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: cloud-api-adaptor-{{ $provider.name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cloud-api-adaptor-{{ $provider.name }}-peerpod-editor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-node-viewer
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-node-viewer
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: cloud-api-adaptor-{{ $provider.name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cloud-api-adaptor-{{ $provider.name }}-node-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-node-status-patcher
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-api-adaptor-{{ $provider.name }}-node-status-patcher
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: cloud-api-adaptor-{{ $provider.name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cloud-api-adaptor-{{ $provider.name }}-node-status-patcher
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
