{{- if .Values.providers }}
{{- range $provider := .Values.providers }}
{{- if include "peerpods.providerEnabled" $provider }}
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ $provider.runtimeClassName }}
  labels:
{{ include "peerpods.providerLabels" (dict "root" $ "provider" $provider) | nindent 4 }}
handler: {{ $provider.runtimeClassName }}
{{- end }}
{{- end }}
{{- end }}
